version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - "16686:16686" # frontend (to inspect traces)
      - "5775:5775"
      - "6831:6831"
      - "6832:6832/udp"
      - "14268:14268"